export const GET_PROCEDURES = "GET_PROCEDURES";
export const CREATE_PROCEDURE = "CREATE_PROCEDURE";
export const UPDATE_PROCEDURE = "UPDATE_PROCEDURE";
export const DELETE_PROCEDURE = "DELETE_PROCEDURE";
